name: Deploy Nginx

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t mynginx .

    - name: Start Nginx container
      run: docker run -d --name mynginx -p 80:80 mynginx

    - name: Wait for Nginx to start
      run: |
        until [[ $(curl -s -o /dev/null -w "%{http_code}" http://localhost) == "200" ]]; do
          sleep 5
        done

    - name: Get Nginx start page
      run: curl -o nginx-start-page.html http://localhost

    - name: Create artifact
      run: tar -czvf nginx-start-page.tar.gz nginx-start-page.html

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nginx-start-page
        path: nginx-start-page.tar.gz
