name: Docker Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t mynginx .

    - name: Run Docker Container
      run: docker run -d -p 80:80 mynginx

    - name: Wait for Docker Container to Start
      run: sleep 5

    - name: Get Index.html Page
      run: docker cp <432bde7e0ecddf6c97ab05a1539a031d1855dad69e17f0f1e558c9ed5d9cbd34>:/usr/share/nginx/html/index.html index.html

    - name: Archive Index.html
      run: tar -cf index.tar index.html

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nginx-artifact
        path: index.tar
