name: Nginx webserver deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . -t my-image

    - name: Run the Docker container
      run: |
        docker run -d -p 80:80 my-image
        sleep 10

    - name: Get the home page
      run: curl -o index.html http://localhost:80 --verbose

    - name: Save home page as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: index.html
